# Generated by Django 5.1.3 on 2024-12-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Patient',
        ),
    ]
