# Generated by Django 5.1.3 on 2025-01-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.IntegerField(unique=True),
        ),
    ]
