# Generated by Django 5.1.3 on 2024-12-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
    ]
