# Generated by Django 5.1.3 on 2025-01-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_patient_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
