# Generated by Django 5.1.3 on 2024-12-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
