# Generated by Django 5.1.3 on 2025-01-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_appointment_token_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
